# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check

on:

  push:
    branches: [ main, master, dev ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]

jobs:

  Check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://continuumio/miniconda3
      - name: Updating conda
        run: conda update --all -y
      - name: Installing tools
        run: conda install -c conda-forge -y flake8 bandit
      - name: Running flake
        run: |
          conda install -c conda-forge -y flake8 bandit
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 . --count --ignore=E272,E501,E266,E241,E226,E251,E303,E221 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 . --count --ignore=E272,E501,E266,E241,E226,E251,E303,E221,E122,E211,E302 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Running bandit
        run: |
          # -lll to only catch the higher level security issues
          python -m bandit -r -lll .
